### ISSUE TITLE
When you click tabs on another windows, the tabs will shift and it will not do the right thing

### ISSUE THREAD

**Issue by shodanx2** [BlackGlory/active-pinned-tab#3]
So when you click another firefox window while you have tabs, as you click it active pinned tab will move the pinned tab to the newly focused window.

This will cause all tabs to shift on the horizontal axis.

So if you click on a tab on that window, maybe expecting to switch to that tab, or to close that tab. It will do something else.

Maybe open an adjacent tab or close your tab or maybe nothing.

This is because the width of the pinned area changes.

What is important is that the tabs don't shift when refocusing windows.

My preferred fix would be that pinned that remain simultaneously present on all windows at all times, just like firefox should already allow in the first place !

Barring that, it could be calculating the current horizontal offset of the tab, calculate how much they shit when moving the pinned tabs over and then shifting them again  into the right position by changing the horizontal position toward the left. This is not going to work if the title bar is not full enough that they can be moved. This will also not work if the tab are already moved all the way to the left. 

This also conflicts with the current action which is to resetting the tab horizontal position to the currently focused tab.

**Comment by BlackGlory** [comment]
Close, because this is not achievable.
In addition, even if the browser allows this, I will not implement it because it takes time.
If you can achieve it, you are welcome to create a PR.
