### ISSUE TITLE
Pinned tabs are lost if you close a window

### ISSUE THREAD

**Issue by shodanx2** [BlackGlory/active-pinned-tab#4]
I am constantly losing my pinned tabs because I often end up closing a whole window.

The only way to close a window is to, first close all tabs except the pinned tabs, then focus another window. 

This is not natural and the end result is that I always end up inadvertently closing my pinned tabs.

**Comment by BlackGlory** [comment]
Close, because this is not achievable.
In addition, even if the browser allows this, I will not implement it because it takes time.
If you can achieve it, you are welcome to create a PR.

**Comment by shodanx2** [comment]
Why close the issue ? I thought this was an open source project ? So it's not only you working on this.
But by closing the issue, you make it invisible as something to fix for anyone else browsing this repository.

**Comment by BlackGlory** [comment]
You don't understand open source, in fact I am the only one doing this, and your feature request is impossible.
